repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix]
        files: ^(engram|sgms|tests|scripts|train\.py)$
      - id: ruff-format
        files: ^(engram|sgms|tests|scripts|train\.py)$
